name: learn-github-actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm -v
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Muahahaha
        env:
          TEST: ${{ secrets.TESTING }}
        run: printf "//npm.pkg.github.com/:_authToken=$TEST\nregistry=https://npm.pkg.github.com/Boardgent" > .npmrc
      - run: cat ~/.npmrc

  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "10.15.3"
      - run: npm install
      - run: node index.js
      - name: something
        run: node -v
      - name: conditional
        if: github.ref == 'refs/heads/main'
        run: echo is in main
  pwd:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
